### ISSUE TITLE
5. 価値基準を満たすための行動

### ISSUE THREAD

**Issue by chachaki** [1on1guide-org/1on1meeting-guide#60]
> 5. 価値基準を満たすための行動
> ここまでに挙げた価値基準を満たすため、以下のような行動が基本となる。
> 状況確認
> • 困っていること、コンディション、悩みがあるかなどを確認する
> 観察
> • 1on1の時間以外も含めて、相手がどんな状況にありそうか観察する
> 並走
> • それぞれの役割はあった上で、一緒に進めていく
> • 部分では牽引や伴走もあるが、全体では並走する
> 内省
> • 自分の状況を自分で把握する
> • 状況と事実と解釈と主観と客観が混ざっていることを踏まえて話してみる・整理する

5. 価値基準を満たすための行動
「4. 1on1の価値基準」に挙げた価値基準を満たすため、以下のような行動が基本となる。

状況確認
以下のようなことを互いに確認する
• 困っていること、悩みがあるか
• 嬉しいことや楽しいこと
•コンディション（体調、仕事の状況、モチベーション）

観察
• 1on1の時間以外も含めて、相手がどんな状況にありそうか観察する

並走
• それぞれの役割はあった上で、一緒に進めていく
• 部分では牽引や伴走もあるが、全体では並走する

内省
• 自分の状況を自分で把握する
• 状況と事実と解釈をまずは話してみて、整理する
• 主観と客観が混ざっていることを互いに踏まえる

**Comment by eroccowaruico** [comment]
リリースしたのでクローズ
